name: shopfloor_app
description: Shop Floor Digitalization App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
